# Generated by Django 5.0 on 2023-12-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='handle',
            new_name='github_handle',
        ),
    ]
