# Generated by Django 5.0 on 2023-12-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_handle_user_github_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_handle',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(unique=True),
        ),
    ]
