# Generated by Django 5.0 on 2023-12-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readme_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readme',
            old_name='github_handle',
            new_name='username',
        ),
    ]
