# Generated by Django 5.0 on 2023-12-11 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readme_app', '0003_rename_github_handle_readme_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='readme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
