# Generated by Django 5.0 on 2023-12-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_app', '0001_initial'),
        ('readme_app', '0004_readme_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readme',
            name='repo_name',
        ),
        migrations.RemoveField(
            model_name='readme',
            name='username',
        ),
        migrations.AddField(
            model_name='readme',
            name='github_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readmes', to='github_app.githubrepository'),
        ),
    ]
