# Generated by Django 5.0 on 2023-12-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readme_app', '0007_readme_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='readme',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
