# Generated by Django 5.0 on 2023-12-08 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmeapp', '0004_readme_github_handle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='readme',
            name='github_handle',
            field=models.ForeignKey(default='Unknown', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readmes', to=settings.AUTH_USER_MODEL),
        ),
    ]
